### ISSUE TITLE
想请教一下tproxy下waydroid联网问题

### ISSUE THREAD

**Issue by kpzhao** [Weathercold/nixfiles#15]
你好，我用了你的xray vless的tproxy的配置，然后在透明代理下waydroid无法正常上网，想用nftables的规则把waydroid排除在外，可是、一直没有成功，想问一下你的waydroid在透明代理时能正常工作吗?

**Comment by kpzhao** [comment]
> 这个我没有测试过，正巧我电脑现在坏了，要测试的话很难。建议去 tg 群问一下

tg群了问过了也没有解决

**Comment by Weathercold** [comment]
你解决问题了吗？

**Comment by kpzhao** [comment]
> 你解决问题了吗？

waydroid不能用透明代理，把waydroid接口的流量排除了
